version: '3'

networks:
  yii:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - yii
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - yii
    links:
      - mysql
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - yii
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: server
    volumes:
      - ./:/var/www/html
    ports:
      - "3012:3012"
    networks:
      - yii
    links:
      - mysql