<?php

namespace app\models;

use phpDocumentor\Reflection\Types\Boolean;
use Yii;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "members".
 *
 * @property int $id
 * @property string|null $first_name
 * @property string|null $last_name
 * @property string $email
 * @property string $auth_key
 * @property string $access_token
 *
 * @property State[] $membersStates
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'members';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email'], 'required'],
            [['first_name', 'last_name'], 'string', 'max' => 255],
            [['email'], 'string', 'max' => 320],
            [['email'], 'unique'],
            [['auth_key', 'access_token'], 'string', 'max' => 32]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'email' => 'Email',
            'auth_key' => 'Auth Key',
            'access_token' => 'Access Token',
        ];
    }

    /**
     * Gets query for [[MembersStates]].
     *
     * @return ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(UserState::className(), ['member_id' => 'id']);
    }

    public function getName()
    {
        return $this->first_name ? $this->first_name . ' ' . $this->last_name : $this->email;
    }

    /**
     * @return bool
     */
    public function getIsHandUp()
    {
        return $this->getState()->one()->is_hand_raised;
    }

    public function isOnline()
    {
        return $this->getOnline()->online;
    }

    /**
     * @return Online
     */
    public function getOnline()
    {
        return Online::find()->byUserId($this->id);
    }

    public function setOnline(bool $val)
    {
        /**
         * @var Online $online
         */
        $online = $this->getOnline();
        if(!$online){
            $online = new Online();
            $online->user_id = $this->id;
        }
        $online->online = $val;
        $online->save();
    }

    public function setHand($isUp)
    {
        $hand = $this->getState()->one();
        $hand->is_hand_raised = $isUp;
        $hand->update();
    }

    /**
     * @param bool $insert
     * @return bool
     * @throws \yii\base\Exception
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->auth_key = \Yii::$app->security->generateRandomString();
            }
            return true;
        }
        return false;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert)
        {
            $state = new UserState();
            $state->member_id = $this->id;
            $state->is_hand_raised = false;
            $state->save();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
